buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.hibernate:hibernate-gradle-plugin:5.6.4.Final"
    }
}





plugins {
    id 'java'
    id 'org.springframework.boot' version '2.7.0'
    id 'io.spring.dependency-management' version '1.1.0'
//    id 'org.hibernate.orm' version '5.6.4.Final'
}





apply plugin: 'org.hibernate.orm'

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}


configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}



dependencies {
    //spring
    implementation "org.springframework.boot:spring-boot-starter-web"

    //lombok
    compileOnly "org.projectlombok:lombok"
    annotationProcessor "org.projectlombok:lombok"
    implementation 'org.liquibase:liquibase-core'
   // implementation 'org.hibernate:hibernate-core:6.2.6.Final'
    runtimeOnly 'org.postgresql:postgresql'

    //testing
    testImplementation "org.springframework.boot:spring-boot-starter-test"
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'net.javacrumbs.shedlock:shedlock-spring:5.3.0'
    implementation 'net.javacrumbs.shedlock:shedlock-provider-jdbc-template:5.3.0'

}

test {
    useJUnitPlatform()
}

 //hibernate {

    //enhance{
//enableLazyInitialization = true
   // }
//}



